In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

import os
import cv2

import matplotlib.pyplot as plt

In [ ]:
def extract_label(img_path,underscore_flag ):
    filename, _ = os.path.splitext(os.path.basename(img_path))

    subject_id, etc = filename.split('__')

    if underscore_flag:
      gender, finger, _, _, _ = etc.split('_')
    else:
      gender, finger, _, _ = etc.split('_')

    gender = 0 if gender == 'M' else 1

    return np.array([gender], dtype=np.uint16)

In [ ]:
def loading_data(path,boolean):
    data = []
    for img in os.listdir(path):
            img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
            img_resize = cv2.resize(img_array, (96,96))
            label = extract_label(os.path.join(path, img),boolean)

            data.append([label[0], img_resize ])

    return data

In [ ]:
path='/content/drive/MyDrive/male'

In [ ]:
data=loading_data(path,False)

In [ ]:
number_of_elements = len(data)

print("Number of elements in the list:", number_of_elements)

Number of elements in the list: 5016


In [ ]:
img, labels = [], []
for label, feature in data:
    labels.append(label)
    img.append(feature)

In [ ]:
x_test,y_test= [], []

In [ ]:
x_test = np.array(img).reshape(-1, 96, 96, 1)
y_test = np.array(labels)
print(x_test.ndim)
print(x_test.shape)
print(y_test.ndim)
print(y_test.shape)

4
(5016, 96, 96, 1)
1
(5016,)


In [ ]:
x_test2 = x_test/255
y_test2 = y_test
print(x_test.ndim)
print(x_test.shape)
print(y_test.ndim)
print(y_test.shape)
print(x_test2[0])

4
(5016, 96, 96, 1)
1
(5016,)
[[[0.62745098]
  [0.61960784]
  [0.61960784]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.62745098]
  [0.41176471]
  [0.4745098 ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.62745098]
  [0.41176471]
  [1.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 ...

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]]


In [ ]:
import joblib

In [ ]:
model=joblib.load('/content/drive/MyDrive/fp_model.joblib')

In [ ]:
model.evaluate(x_test,y_test)

157/157 [==============================] - 16s 99ms/step - loss: 1.6117 - accuracy: 0.9968


[1.6117167472839355, 0.9968101978302002]

In [ ]:
model.evaluate(x_test2,y_test2)

157/157 [==============================] - 15s 96ms/step - loss: 0.0015 - accuracy: 0.9998


[0.0015445133903995156, 0.9998006224632263]

In [ ]:
predictions = model.predict(x_test)


157/157 [==============================] - 16s 102ms/step


In [ ]:
print(predictions.ndim)
print(predictions.shape)

2
(5016, 1)


In [ ]:
predictions2 = model.predict(x_test2)
print(predictions2.ndim)
print(predictions2.shape)

157/157 [==============================] - 15s 98ms/step
2
(5016, 1)


In [ ]:
print(predictions[0])

[0.]


In [ ]:
print(predictions2[0])

[3.077128e-15]


In [ ]:
predictions = (predictions >= 0.5).astype(np.int32)

In [ ]:
print(predictions)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
male_cnt=0
female_cnt=0
for gender in np.nditer(predictions):
    if gender ==0:
     print("Male",end=" ")
     male_cnt+=1
    else:
     print("Female",end=" ")
     female_cnt+=1
print("\n males predicted:",male_cnt)
print("\n females predicted:",female_cnt)

Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male M

In [ ]:
acc=(male_cnt/number_of_elements)*100
print("accuracy is:",acc)

accuracy is: 95.41467304625199


In [ ]:
predictions2 = (predictions2 >= 0.5).astype(np.int32)

In [ ]:
print(predictions2)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [ ]:
male_cnt2=0
female_cnt2=0
for gender in np.nditer(predictions2):
    if gender ==0:
     print("Male",end=" ")
     male_cnt2+=1
    else:
     print("Female",end=" ")
     female_cnt2+=1
print("\n males predicted:",male_cnt2)
print("\n females predicted:",female_cnt2)

Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Female Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male Male M

In [ ]:
acc2=(male_cnt2/number_of_elements)*100
print("accuracy is:",acc2)#Male folder e onek kota bhul kore female copy hoye bose ache

accuracy is: 95.07575757575758
