In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

import os
import cv2

import matplotlib.pyplot as plt

In [ ]:
def extract_label(img_path,underscore_flag ):
    filename, _ = os.path.splitext(os.path.basename(img_path))

    subject_id, etc = filename.split('__')

    if underscore_flag:
      gender,lr, finger, _, _ = etc.split('_')
    else:
      gender,lr, finger,  _ = etc.split('_')

    if finger == 'thumb':
        finger = 0
    elif finger == 'index':
        finger = 1
    elif finger == 'middle':
        finger = 2
    elif finger == 'ring':
        finger = 3
    elif finger == 'little':
        finger = 4

    return np.array([finger], dtype=np.uint16)

In [ ]:
def loading_data(path,boolean):
    data = []

    for img in os.listdir(path):
            img_array = cv2.imread(os.path.join(path, img), cv2.IMREAD_GRAYSCALE)
            img_resize = cv2.resize(img_array, (96,96))
            label = extract_label(os.path.join(path, img),boolean)
            data.append([label[0], img_resize ])


    return data

In [ ]:
path='/content/drive/MyDrive/thumb'

In [ ]:
data=loading_data(path,False)


In [ ]:
number_of_elements = len(data)

print("Number of elements in the list:", number_of_elements)

Number of elements in the list: 1200


In [ ]:
img, labels = [], []
for label, feature in data:
    labels.append(label)
    img.append(feature)

In [ ]:
x_test,y_test= [], []

In [ ]:
x_test2,y_test2= [], []

In [ ]:
x_test = np.array(img).reshape(-1, 96, 96, 1)
y_test = np.array(labels)
print(x_test.ndim)
print(x_test.shape)
print(y_test.ndim)
print(y_test.shape)
print(x_test[0])

4
(1200, 96, 96, 1)
1
(1200,)
[[[160]
  [158]
  [158]
  ...
  [  0]
  [  0]
  [  0]]

 [[160]
  [105]
  [121]
  ...
  [  0]
  [  0]
  [  0]]

 [[160]
  [105]
  [255]
  ...
  [  0]
  [  0]
  [  0]]

 ...

 [[  0]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  ...
  [  0]
  [  0]
  [  0]]]


In [ ]:
x_test2 = x_test/255
y_test2 = y_test
print(x_test.ndim)
print(x_test.shape)
print(y_test.ndim)
print(y_test.shape)
print(x_test2[0])

4
(1200, 96, 96, 1)
1
(1200,)
[[[0.62745098]
  [0.61960784]
  [0.61960784]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.62745098]
  [0.41176471]
  [0.4745098 ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.62745098]
  [0.41176471]
  [1.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 ...

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.        ]
  [0.        ]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]]


In [ ]:
import joblib

In [ ]:
model=joblib.load('/content/drive/MyDrive/fp_model_finger.joblib')

In [ ]:
model.evaluate(x_test,y_test)

38/38 [==============================] - 13s 345ms/step - loss: 13.6283 - accuracy: 0.9642


[13.628304481506348, 0.9641666412353516]

In [ ]:
model.evaluate(x_test2,y_test2)

38/38 [==============================] - 13s 345ms/step - loss: 0.0476 - accuracy: 0.9883


[0.047580379992723465, 0.9883333444595337]

In [ ]:
cnt=0

In [ ]:
predictions = model.predict(x_test)
predictions2 = model.predict(x_test2)

38/38 [==============================] - 13s 343ms/step


In [ ]:
print(predictions.ndim)
print(predictions.shape)


2
(1200, 5)


In [ ]:
print(predictions2.ndim)
print(predictions2.shape)

2
(1200, 5)


In [ ]:
print(predictions[0])

[0.99999994 0.         0.         0.         0.        ]


In [ ]:
print(predictions2[0])

[9.9994820e-01 5.0808951e-05 1.6399318e-07 7.7622445e-07 5.3629817e-10]


In [ ]:
thumb_cnt=0
index_cnt=0
middle_cnt=0
ring_cnt=0
little_cnt=0

predicted = [np.argmax(i) for i in predictions]
print(type(predicted))
predicted=np.array(predicted)
aa=[predictions[i][predicted]for i in range(len(predictions))]
print(f"Index of the maximum element: {predicted}")
for finger in np.nditer(predicted):
    if finger ==0:
     print("thumb",end=" ")
     thumb_cnt+=1
    elif finger == 1:
         print("index",end=" ")
         index_cnt+=1
    elif finger == 2:
         print("middle",end=" ")
         middle_cnt+=1
    elif finger ==3:
         print("ring",end=" ")
         ring_cnt+=1
    elif finger == 4:
         print("little",end=" ")
         little_cnt+=1

print("\n",thumb_cnt, " \n", index_cnt," \n",middle_cnt,"\n ",ring_cnt,"\n ",little_cnt,"\n ")

<class 'list'>
Index of the maximum element: [0 0 0 ... 3 0 0]
thumb thumb thumb thumb thumb index thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb ring thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb ring thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb ring thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb index thumb thumb thumb thumb ring ring thumb thumb thumb thumb ring thumb thumb thumb t

In [ ]:
acc=(thumb_cnt/number_of_elements)*100
print("accuracy is:",acc)

accuracy is: 96.41666666666666


In [ ]:
thumb_cnt2=0
index_cnt2=0
middle_cnt2=0
ring_cnt2=0
little_cnt2=0

predicted2= [np.argmax(i) for i in predictions2]
print(type(predicted2))
predicted2=np.array(predicted2)
aa=[predictions2[i][predicted2]for i in range(len(predictions2))]
print(f"Index of the maximum element: {predicted2}")
for finger in np.nditer(predicted2):
    if finger ==0:
     print("thumb",end=" ")
     thumb_cnt2+=1
    elif finger == 1:
         print("index",end=" ")
         index_cnt2+=1
    elif finger == 2:
         print("middle",end=" ")
         middle_cnt2+=1
    elif finger ==3:
         print("ring",end=" ")
         ring_cnt2+=1
    elif finger == 4:
         print("little",end=" ")
         little_cnt2+=1

print("\n",thumb_cnt2, " \n", index_cnt2," \n",middle_cnt2,"\n ",ring_cnt2,"\n ",little_cnt2,"\n ")

<class 'list'>
Index of the maximum element: [0 0 0 ... 0 0 0]
thumb thumb thumb thumb thumb index thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb ring thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb index thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb thumb th

In [ ]:
acc2=(thumb_cnt2/number_of_elements)*100
print("accuracy is:",acc2)

accuracy is: 98.83333333333333
